name: Update Filters

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allow manual run

jobs:
  update-filters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # We'll manually set token for push

      - name: Install tools
        run: sudo apt-get install -y curl

      - name: Download EasyList & EasyPrivacy
        run: |
          curl -s https://easylist.to/easylist/easylist.txt -o easylist.txt
          curl -s https://easylist.to/easylist/easyprivacy.txt -o easyprivacy.txt

      - name: Merge with custom rules
        run: |
          echo "! Custom rules" > filters.txt
          if [ -f custom.txt ]; then cat custom.txt >> filters.txt; fi
          echo "" >> filters.txt
          echo "! EasyList" >> filters.txt
          cat easylist.txt >> filters.txt
          echo "" >> filters.txt
          echo "! EasyPrivacy" >> filters.txt
          cat easyprivacy.txt >> filters.txt

      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filters.txt
          git commit -m "Update filters [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Wiliam2001/my-adblock-list.git
