name: Update Filters

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch: # Allow manual run

permissions:
  contents: write  # ✅ allow commit/push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download EasyList & EasyPrivacy
        run: |
          curl -s https://easylist.to/easylist/easylist.txt -o easylist.txt
          curl -s https://easylist.to/easylist/easyprivacy.txt -o easyprivacy.txt

      - name: Download uBlock filters
        run: |
          curl -s https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt -o ublock.txt

      - name: Merge with custom rules
        run: |
          echo "! Last updated: $(date -u)" > filters.txt
          cat easylist.txt easyprivacy.txt ublock.txt custom.txt >> filters.txt
          rm easylist.txt easyprivacy.txt ublock.txt
          echo "✅ Merged $(wc -l < filters.txt) rules."

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filters.txt
          git commit -m "Update filters [skip ci]" || echo "No changes to commit"
          git push
