name: Update AdBlock Filters

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch & Merge Lists
        run: |
          mkdir -p tmp
          curl -s https://easylist.to/easylist/easylist.txt -o tmp/easylist.txt
          curl -s https://easylist.to/easylist/easyprivacy.txt -o tmp/easyprivacy.txt
          curl -s https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/filters.txt -o tmp/ublock-filters.txt
          curl -s https://raw.githubusercontent.com/Wiliam2001/my-adblock-list/main/custom.txt -o tmp/custom.txt

          cat tmp/easylist.txt tmp/easyprivacy.txt tmp/ublock-filters.txt tmp/custom.txt \
            | grep -v "^\!" \
            | grep -v "^\[Adblock" \
            | sort -u \
            > filters.txt

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filters.txt
          git commit -m "Update filters [skip ci]" || echo "No changes to commit"
          git push
